# Generated by Django 4.0.6 on 2022-08-13 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('dob', models.DateField(default=datetime.datetime(2022, 8, 13, 8, 24, 56, 22164))),
                ('district', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('acc_type', models.CharField(blank=True, max_length=20)),
                ('materials', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(null=True)),
                ('address_full', models.TextField(null=True)),
                ('zip', models.PositiveIntegerField()),
            ],
        ),
    ]
