# Generated by Django 4.0.6 on 2022-08-13 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 8, 13, 8, 26, 32, 158339)),
        ),
    ]
