# Generated by Django 4.0.6 on 2022-08-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_application_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.DateField(default=True),
        ),
    ]
